/**
 * Audio alignment data for LibriVox chapter recordings.
 *
 * Each chapter's alignment was generated by:
 * 1. Downloading the LibriVox MP3 from archive.org
 * 2. Running it through OpenAI Whisper (base model) for word-level timestamps
 * 3. Fuzzy-matching the Whisper transcript against the chapter text to find
 *    where each paragraph starts and ends in the audio
 *
 * All audio recordings are by LibriVox volunteers and are in the Public Domain (USA).
 * Credit each reader by name — they donated their time to make these recordings.
 */

export interface ParagraphTimestamp {
  paragraph_index: number
  start_time: number
  end_time: number
}

export interface AudioAlignment {
  chapter_number: number
  title: string
  reader: string
  audio_url: string
  audio_duration: number
  paragraphs: ParagraphTimestamp[]
  // Multi-file chapters (e.g., Ch1 Section 3 = 3 audio files)
  audio_parts?: {
    url: string
    reader: string
    offset: number
    duration: number
  }[]
  readers?: string[]
  total_duration?: number
}

// Static imports — these are bundled at build time
// Only import chapters that have alignment data
import chapter1 from '@/data/audio-alignments/chapter_1.json'
import chapter2 from '@/data/audio-alignments/chapter_2.json'
import chapter3 from '@/data/audio-alignments/chapter_3.json'
import chapter4 from '@/data/audio-alignments/chapter_4.json'

const alignments: Record<number, AudioAlignment> = {
  1: chapter1 as AudioAlignment,
  2: chapter2 as AudioAlignment,
  3: chapter3 as AudioAlignment,
  4: chapter4 as AudioAlignment,
}

/**
 * Get audio alignment data for a chapter, if available.
 * Returns null if no alignment exists for this chapter yet.
 */
export function getAudioAlignment(chapterNumber: number): AudioAlignment | null {
  return alignments[chapterNumber] || null
}

/**
 * Check whether a chapter has audio alignment data.
 */
export function hasAudioAlignment(chapterNumber: number): boolean {
  return chapterNumber in alignments
}
