'use client'

import { useState, useEffect, useRef, useCallback } from 'react'

/**
 * AudioPlayer — Audiobook-style player for chapter readings
 *
 * Plays LibriVox recordings of Capital and syncs paragraph highlights
 * to the audio position. Each paragraph's timestamp was generated by
 * running the audio through Whisper and fuzzy-matching the transcript
 * against the chapter text.
 *
 * Features:
 * - Play/pause with spacebar (when not in input)
 * - Paragraph highlight synced to audio position
 * - Click any paragraph to jump to that point in the audio
 * - Speed control (0.75x–2x)
 * - Skip forward/back 15 seconds
 * - Auto-scroll to keep current paragraph visible
 * - Credits the specific LibriVox volunteer reader
 */

interface ParagraphTimestamp {
  paragraph_index: number
  start_time: number
  end_time: number
}

interface AudioAlignment {
  chapter_number: number
  title: string
  reader: string
  audio_url: string
  audio_duration: number
  paragraphs: ParagraphTimestamp[]
  // Multi-file chapters
  audio_parts?: {
    url: string
    reader: string
    offset: number
    duration: number
  }[]
  readers?: string[]
  total_duration?: number
}

interface AudioPlayerProps {
  alignment: AudioAlignment | null
  onParagraphChange?: (paragraphIndex: number | null) => void
  onPlayStateChange?: (playing: boolean) => void
  footnotesExpanded?: boolean
  onFootnotesToggle?: () => void
}

const PROGRESS_KEY_PREFIX = 'ccp-audio-progress-'

function getSavedProgress(chapterNumber: number): { time: number; rate: number } | null {
  try {
    const saved = localStorage.getItem(`${PROGRESS_KEY_PREFIX}${chapterNumber}`)
    if (saved) return JSON.parse(saved)
  } catch { /* ignore */ }
  return null
}

function saveProgress(chapterNumber: number, time: number, rate: number) {
  try {
    localStorage.setItem(`${PROGRESS_KEY_PREFIX}${chapterNumber}`, JSON.stringify({ time, rate }))
  } catch { /* ignore */ }
}

export default function AudioPlayer({ alignment, onParagraphChange, onPlayStateChange, footnotesExpanded, onFootnotesToggle }: AudioPlayerProps) {
  // Restore saved progress for this chapter
  const savedProgress = alignment ? getSavedProgress(alignment.chapter_number) : null

  const [isPlaying, setIsPlaying] = useState(false)
  const [currentTime, setCurrentTime] = useState(savedProgress?.time || 0)
  const [duration, setDuration] = useState(0)
  const [playbackRate, setPlaybackRate] = useState(savedProgress?.rate || 1)
  const [isLoading, setIsLoading] = useState(false)
  // Auto-expand if there's saved progress (user was listening before)
  const [isExpanded, setIsExpanded] = useState(!!savedProgress?.time)
  const [currentParagraph, setCurrentParagraph] = useState<number | null>(null)
  const audioRef = useRef<HTMLAudioElement | null>(null)
  const animationRef = useRef<number | null>(null)
  const lastParagraphRef = useRef<number | null>(null)
  const lastUIUpdateRef = useRef<number>(0)

  // Don't render if no alignment data
  if (!alignment) return null

  // For multi-file chapters, use the first audio part's URL
  // TODO: Support playing through all parts sequentially
  const audioUrl = alignment.audio_url || alignment.audio_parts?.[0]?.url || ''
  const reader = alignment.reader || (alignment.readers ? alignment.readers.join(', ') : 'Unknown')
  const totalDuration = alignment.audio_duration || alignment.total_duration || 0

  // ── Time tracking loop ──
  // Throttle UI state updates to ~4/sec to avoid excessive re-renders,
  // but check paragraph boundaries at full rAF speed.
  const updateTime = useCallback(() => {
    if (audioRef.current) {
      const time = audioRef.current.currentTime
      const now = performance.now()
      // Update React state (and thus the progress bar) ~4 times per second
      if (now - lastUIUpdateRef.current > 250) {
        setCurrentTime(time)
        lastUIUpdateRef.current = now
        // Save progress every ~5 seconds (every 20th UI update)
        if (alignment && Math.floor(now / 5000) !== Math.floor((now - 250) / 5000)) {
          saveProgress(alignment.chapter_number, time, audioRef.current?.playbackRate || 1)
        }
      }

      // Find which paragraph we're in
      if (alignment) {
        let foundPara: number | null = null
        for (const p of alignment.paragraphs) {
          if (time >= p.start_time && time < p.end_time) {
            foundPara = p.paragraph_index
            break
          }
        }
        if (foundPara !== lastParagraphRef.current) {
          lastParagraphRef.current = foundPara
          setCurrentParagraph(foundPara)
          onParagraphChange?.(foundPara)
        }
      }
    }
    animationRef.current = requestAnimationFrame(updateTime)
  }, [alignment, onParagraphChange])

  // ── Play/Pause ──
  const togglePlay = useCallback(() => {
    if (!audioRef.current) return
    if (isPlaying) {
      audioRef.current.pause()
      if (animationRef.current) cancelAnimationFrame(animationRef.current)
      // Force final time update so progress bar shows exact position
      setCurrentTime(audioRef.current.currentTime)
      // Save position for resume on refresh / device switch
      if (alignment) saveProgress(alignment.chapter_number, audioRef.current.currentTime, playbackRate)
    } else {
      audioRef.current.play()
      animationRef.current = requestAnimationFrame(updateTime)
    }
    const newState = !isPlaying
    setIsPlaying(newState)
    onPlayStateChange?.(newState)
  }, [isPlaying, updateTime, onPlayStateChange])

  // ── Skip ──
  const skip = useCallback((seconds: number) => {
    if (!audioRef.current) return
    audioRef.current.currentTime = Math.max(0, Math.min(
      audioRef.current.currentTime + seconds,
      audioRef.current.duration || 0
    ))
  }, [])

  // ── Jump to paragraph ──
  const jumpToParagraph = useCallback((paragraphIndex: number) => {
    if (!audioRef.current || !alignment) return
    const para = alignment.paragraphs.find(p => p.paragraph_index === paragraphIndex)
    if (para) {
      audioRef.current.currentTime = para.start_time
      if (!isPlaying) {
        audioRef.current.play()
        setIsPlaying(true)
        animationRef.current = requestAnimationFrame(updateTime)
      }
    }
  }, [alignment, isPlaying, updateTime])

  // ── Speed control ──
  const cycleSpeed = useCallback(() => {
    const speeds = [0.75, 1, 1.25, 1.5, 2]
    const currentIdx = speeds.indexOf(playbackRate)
    const nextIdx = (currentIdx + 1) % speeds.length
    const newRate = speeds[nextIdx]
    setPlaybackRate(newRate)
    if (audioRef.current) audioRef.current.playbackRate = newRate
  }, [playbackRate])

  // ── Keyboard shortcuts ──
  useEffect(() => {
    if (!isExpanded) return

    const handleKeyDown = (e: KeyboardEvent) => {
      const tag = (e.target as HTMLElement).tagName
      if (tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT') return
      if ((e.target as HTMLElement).isContentEditable) return

      if (e.code === 'Space') {
        e.preventDefault()
        togglePlay()
      } else if (e.key === 'ArrowLeft') {
        e.preventDefault()
        skip(-15)
      } else if (e.key === 'ArrowRight') {
        e.preventDefault()
        skip(15)
      }
    }

    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [isExpanded, togglePlay, skip])

  // ── Save on tab close / navigate away — belt and suspenders ──
  useEffect(() => {
    const handleBeforeUnload = () => {
      if (audioRef.current && alignment) {
        saveProgress(alignment.chapter_number, audioRef.current.currentTime, audioRef.current.playbackRate)
      }
    }
    // visibilitychange catches mobile tab switches and app backgrounding
    const handleVisibilityChange = () => {
      if (document.hidden && audioRef.current && alignment) {
        saveProgress(alignment.chapter_number, audioRef.current.currentTime, audioRef.current.playbackRate)
      }
    }
    window.addEventListener('beforeunload', handleBeforeUnload)
    document.addEventListener('visibilitychange', handleVisibilityChange)
    return () => {
      window.removeEventListener('beforeunload', handleBeforeUnload)
      document.removeEventListener('visibilitychange', handleVisibilityChange)
    }
  }, [alignment])

  // ── Cleanup ──
  useEffect(() => {
    return () => {
      if (animationRef.current) cancelAnimationFrame(animationRef.current)
      if (audioRef.current) {
        // Save position before cleanup
        if (alignment) saveProgress(alignment.chapter_number, audioRef.current.currentTime, audioRef.current.playbackRate)
        audioRef.current.pause()
        audioRef.current = null
      }
    }
  }, [])

  // ── Audio element setup ──
  useEffect(() => {
    if (!audioUrl) return

    const audio = new Audio()
    audio.preload = 'metadata'
    audio.src = audioUrl
    audioRef.current = audio

    audio.addEventListener('loadedmetadata', () => {
      setDuration(audio.duration)
      setIsLoading(false)
      // Restore saved position
      if (savedProgress?.time && savedProgress.time < audio.duration) {
        audio.currentTime = savedProgress.time
      }
      if (savedProgress?.rate) {
        audio.playbackRate = savedProgress.rate
      }
    })
    audio.addEventListener('ended', () => {
      setIsPlaying(false)
      onPlayStateChange?.(false)
      if (animationRef.current) cancelAnimationFrame(animationRef.current)
      setCurrentParagraph(null)
      onParagraphChange?.(null)
    })
    audio.addEventListener('waiting', () => setIsLoading(true))
    audio.addEventListener('canplay', () => setIsLoading(false))

    return () => {
      audio.pause()
      audio.src = ''
    }
  }, [audioUrl, onParagraphChange])

  // Expose jumpToParagraph on the window for ChapterReader to call
  useEffect(() => {
    (window as unknown as Record<string, unknown>).__audioPlayerJumpTo = jumpToParagraph
    return () => { delete (window as unknown as Record<string, unknown>).__audioPlayerJumpTo }
  }, [jumpToParagraph])

  // ── Format time ──
  const formatTime = (seconds: number) => {
    const m = Math.floor(seconds / 60)
    const s = Math.floor(seconds % 60)
    return `${m}:${s.toString().padStart(2, '0')}`
  }

  // ── Progress percentage ──
  const progress = duration > 0 ? (currentTime / duration) * 100 : 0

  // ── Seek on progress bar click + drag ──
  const seekBarRef = useRef<HTMLDivElement>(null)
  const isDraggingSeek = useRef(false)

  const seekToPosition = useCallback((clientX: number) => {
    if (!audioRef.current || !duration || !seekBarRef.current) return
    const rect = seekBarRef.current.getBoundingClientRect()
    const ratio = Math.max(0, Math.min(1, (clientX - rect.left) / rect.width))
    audioRef.current.currentTime = ratio * duration
    setCurrentTime(ratio * duration)
  }, [duration])

  const handleSeekStart = useCallback((clientX: number) => {
    isDraggingSeek.current = true
    seekToPosition(clientX)
  }, [seekToPosition])

  const handleSeek = (e: React.MouseEvent<HTMLDivElement>) => {
    handleSeekStart(e.clientX)
  }

  // Mouse drag for seeking
  useEffect(() => {
    const handleMouseMove = (e: MouseEvent) => {
      if (isDraggingSeek.current) seekToPosition(e.clientX)
    }
    const handleMouseUp = () => { isDraggingSeek.current = false }
    window.addEventListener('mousemove', handleMouseMove)
    window.addEventListener('mouseup', handleMouseUp)
    return () => {
      window.removeEventListener('mousemove', handleMouseMove)
      window.removeEventListener('mouseup', handleMouseUp)
    }
  }, [seekToPosition])

  // Touch drag for seeking
  const handleTouchStart = useCallback((e: React.TouchEvent) => {
    isDraggingSeek.current = true
    seekToPosition(e.touches[0].clientX)
  }, [seekToPosition])

  const handleTouchMove = useCallback((e: React.TouchEvent) => {
    if (isDraggingSeek.current) seekToPosition(e.touches[0].clientX)
  }, [seekToPosition])

  const handleTouchEnd = useCallback(() => {
    isDraggingSeek.current = false
  }, [])

  // ── Collapsed state: just a small "Listen" button ──
  if (!isExpanded) {
    return (
      <button
        onClick={() => setIsExpanded(true)}
        className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium btn-transition"
        style={{
          backgroundColor: 'var(--bg-card)',
          color: 'var(--text-primary)',
          border: '1px solid var(--border-default)',
        }}
      >
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M3 18v-6a9 9 0 0 1 18 0v6" />
          <path d="M21 19a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3zM3 19a2 2 0 0 0 2 2h1a2 2 0 0 0 2-2v-3a2 2 0 0 0-2-2H3z" />
        </svg>
        Listen to this chapter
        <span className="text-xs" style={{ color: 'var(--text-secondary)' }}>
          · {formatTime(totalDuration)} · Read by {reader}
        </span>
      </button>
    )
  }

  // ── Expanded: floating pill/bubble (matches the WPM pacer strip style) ──
  return (
    <div
      className="fixed z-50 animate-fade-in"
      style={{
        bottom: '5rem',
        /* Center within the reading area (viewport minus sidebar) */
        left: 'var(--sidebar-width, 0px)',
        right: 0,
        display: 'flex',
        justifyContent: 'center',
        pointerEvents: 'none',
      }}
    >
      <div
        className="flex items-center gap-3 px-4 py-2.5 rounded-full shadow-lg"
        style={{
          pointerEvents: 'auto',
          backgroundColor: 'var(--bg-card)',
          border: '1px solid var(--border-default)',
        }}
      >
        {/* Skip back 15s */}
        <button
          onClick={() => skip(-15)}
          className="flex items-center gap-0.5 px-2 py-1 rounded-full btn-transition text-[11px] font-medium"
          style={{ color: 'var(--text-secondary)', backgroundColor: 'var(--bg-soft)' }}
          aria-label="Skip back 15 seconds"
        >
          <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M11 17l-5-5 5-5" /><path d="M18 17l-5-5 5-5" />
          </svg>
          15s
        </button>

        {/* Play/Pause */}
        <button
          onClick={togglePlay}
          className="w-8 h-8 flex items-center justify-center rounded-full btn-transition"
          style={{
            backgroundColor: isPlaying ? 'var(--accent-purple)' : 'var(--bg-soft)',
            color: isPlaying ? 'var(--text-inverse)' : 'var(--text-primary)',
          }}
          aria-label={isPlaying ? 'Pause' : 'Play'}
        >
          {isLoading ? (
            <svg width="14" height="14" viewBox="0 0 24 24" className="animate-spin">
              <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="2" fill="none" strokeDasharray="30 60" />
            </svg>
          ) : isPlaying ? (
            <span className="text-xs">⏸</span>
          ) : (
            <span className="text-xs">▶</span>
          )}
        </button>

        {/* Skip forward 15s */}
        <button
          onClick={() => skip(15)}
          className="flex items-center gap-0.5 px-2 py-1 rounded-full btn-transition text-[11px] font-medium"
          style={{ color: 'var(--text-secondary)', backgroundColor: 'var(--bg-soft)' }}
          aria-label="Skip forward 15 seconds"
        >
          15s
          <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M13 17l5-5-5-5" /><path d="M6 17l5-5-5-5" />
          </svg>
        </button>

        {/* Seekable progress bar — click or drag to scrub */}
        <div
          ref={seekBarRef}
          className="h-2 rounded-full cursor-pointer relative"
          style={{ width: 'clamp(160px, 25vw, 320px)', backgroundColor: 'var(--bg-soft)' }}
          onMouseDown={handleSeek}
          onTouchStart={handleTouchStart}
          onTouchMove={handleTouchMove}
          onTouchEnd={handleTouchEnd}
          role="slider"
          aria-label="Audio progress — drag to scrub"
          aria-valuemin={0}
          aria-valuemax={100}
          aria-valuenow={Math.round(progress)}
        >
          <div
            className="h-full rounded-full"
            style={{
              width: `${progress}%`,
              backgroundColor: 'var(--accent-purple)',
              transition: 'width 100ms linear',
            }}
          />
        </div>

        {/* Time */}
        <span
          className="text-xs font-semibold tabular-nums min-w-[4.5rem] text-center"
          style={{ color: 'var(--text-primary)' }}
        >
          {formatTime(currentTime)}
          <span className="text-[10px] font-normal mx-0.5" style={{ color: 'var(--text-secondary)' }}>/</span>
          {formatTime(duration || totalDuration)}
        </span>

        {/* Speed */}
        <button
          onClick={cycleSpeed}
          className="w-7 h-7 flex items-center justify-center rounded-full text-[10px] font-bold btn-transition"
          style={{ color: 'var(--text-secondary)', backgroundColor: 'var(--bg-soft)' }}
          aria-label={`Playback speed: ${playbackRate}x`}
        >
          {playbackRate}×
        </button>

        {/* Close */}
        <button
          onClick={() => {
            if (isPlaying) {
              audioRef.current?.pause()
              setIsPlaying(false)
              onPlayStateChange?.(false)
              if (animationRef.current) cancelAnimationFrame(animationRef.current)
            }
            setIsExpanded(false)
          }}
          className="w-6 h-6 flex items-center justify-center rounded-full btn-transition"
          style={{ color: 'var(--text-secondary)' }}
          aria-label="Close audio player"
        >
          <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" />
          </svg>
        </button>
      </div>
    </div>
  )
}
