'use client'

import { useState, useEffect, useRef, useCallback } from 'react'

/**
 * AudioPlayer — Audiobook-style player for chapter readings
 *
 * Plays LibriVox recordings of Capital and syncs paragraph highlights
 * to the audio position. Each paragraph's timestamp was generated by
 * running the audio through Whisper and fuzzy-matching the transcript
 * against the chapter text.
 *
 * Features:
 * - Play/pause with spacebar (when not in input)
 * - Paragraph highlight synced to audio position
 * - Click any paragraph to jump to that point in the audio
 * - Speed control (0.75x–2x)
 * - Skip forward/back 15 seconds
 * - Auto-scroll to keep current paragraph visible
 * - Credits the specific LibriVox volunteer reader
 */

interface ParagraphTimestamp {
  paragraph_index: number
  start_time: number
  end_time: number
}

interface AudioAlignment {
  chapter_number: number
  title: string
  reader: string
  audio_url: string
  audio_duration: number
  paragraphs: ParagraphTimestamp[]
  // Multi-file chapters
  audio_parts?: {
    url: string
    reader: string
    offset: number
    duration: number
  }[]
  readers?: string[]
  total_duration?: number
}

interface AudioPlayerProps {
  alignment: AudioAlignment | null
  onParagraphChange?: (paragraphIndex: number | null) => void
}

export default function AudioPlayer({ alignment, onParagraphChange }: AudioPlayerProps) {
  const [isPlaying, setIsPlaying] = useState(false)
  const [currentTime, setCurrentTime] = useState(0)
  const [duration, setDuration] = useState(0)
  const [playbackRate, setPlaybackRate] = useState(1)
  const [isLoading, setIsLoading] = useState(false)
  const [isExpanded, setIsExpanded] = useState(false)
  const [currentParagraph, setCurrentParagraph] = useState<number | null>(null)
  const audioRef = useRef<HTMLAudioElement | null>(null)
  const animationRef = useRef<number | null>(null)
  const lastParagraphRef = useRef<number | null>(null)

  // Don't render if no alignment data
  if (!alignment) return null

  // For multi-file chapters, use the first audio part's URL
  // TODO: Support playing through all parts sequentially
  const audioUrl = alignment.audio_url || alignment.audio_parts?.[0]?.url || ''
  const reader = alignment.reader || (alignment.readers ? alignment.readers.join(', ') : 'Unknown')
  const totalDuration = alignment.audio_duration || alignment.total_duration || 0

  // ── Time tracking loop ──
  const updateTime = useCallback(() => {
    if (audioRef.current) {
      const time = audioRef.current.currentTime
      setCurrentTime(time)

      // Find which paragraph we're in
      if (alignment) {
        let foundPara: number | null = null
        for (const p of alignment.paragraphs) {
          if (time >= p.start_time && time < p.end_time) {
            foundPara = p.paragraph_index
            break
          }
        }
        if (foundPara !== lastParagraphRef.current) {
          lastParagraphRef.current = foundPara
          setCurrentParagraph(foundPara)
          onParagraphChange?.(foundPara)
        }
      }
    }
    animationRef.current = requestAnimationFrame(updateTime)
  }, [alignment, onParagraphChange])

  // ── Play/Pause ──
  const togglePlay = useCallback(() => {
    if (!audioRef.current) return
    if (isPlaying) {
      audioRef.current.pause()
      if (animationRef.current) cancelAnimationFrame(animationRef.current)
    } else {
      audioRef.current.play()
      animationRef.current = requestAnimationFrame(updateTime)
    }
    setIsPlaying(!isPlaying)
  }, [isPlaying, updateTime])

  // ── Skip ──
  const skip = useCallback((seconds: number) => {
    if (!audioRef.current) return
    audioRef.current.currentTime = Math.max(0, Math.min(
      audioRef.current.currentTime + seconds,
      audioRef.current.duration || 0
    ))
  }, [])

  // ── Jump to paragraph ──
  const jumpToParagraph = useCallback((paragraphIndex: number) => {
    if (!audioRef.current || !alignment) return
    const para = alignment.paragraphs.find(p => p.paragraph_index === paragraphIndex)
    if (para) {
      audioRef.current.currentTime = para.start_time
      if (!isPlaying) {
        audioRef.current.play()
        setIsPlaying(true)
        animationRef.current = requestAnimationFrame(updateTime)
      }
    }
  }, [alignment, isPlaying, updateTime])

  // ── Speed control ──
  const cycleSpeed = useCallback(() => {
    const speeds = [0.75, 1, 1.25, 1.5, 2]
    const currentIdx = speeds.indexOf(playbackRate)
    const nextIdx = (currentIdx + 1) % speeds.length
    const newRate = speeds[nextIdx]
    setPlaybackRate(newRate)
    if (audioRef.current) audioRef.current.playbackRate = newRate
  }, [playbackRate])

  // ── Keyboard shortcuts ──
  useEffect(() => {
    if (!isExpanded) return

    const handleKeyDown = (e: KeyboardEvent) => {
      const tag = (e.target as HTMLElement).tagName
      if (tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT') return
      if ((e.target as HTMLElement).isContentEditable) return

      if (e.code === 'Space') {
        e.preventDefault()
        togglePlay()
      } else if (e.key === 'ArrowLeft') {
        e.preventDefault()
        skip(-15)
      } else if (e.key === 'ArrowRight') {
        e.preventDefault()
        skip(15)
      }
    }

    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [isExpanded, togglePlay, skip])

  // ── Cleanup ──
  useEffect(() => {
    return () => {
      if (animationRef.current) cancelAnimationFrame(animationRef.current)
      if (audioRef.current) {
        audioRef.current.pause()
        audioRef.current = null
      }
    }
  }, [])

  // ── Audio element setup ──
  useEffect(() => {
    if (!audioUrl) return

    const audio = new Audio()
    audio.preload = 'metadata'
    audio.src = audioUrl
    audioRef.current = audio

    audio.addEventListener('loadedmetadata', () => {
      setDuration(audio.duration)
      setIsLoading(false)
    })
    audio.addEventListener('ended', () => {
      setIsPlaying(false)
      if (animationRef.current) cancelAnimationFrame(animationRef.current)
      setCurrentParagraph(null)
      onParagraphChange?.(null)
    })
    audio.addEventListener('waiting', () => setIsLoading(true))
    audio.addEventListener('canplay', () => setIsLoading(false))

    return () => {
      audio.pause()
      audio.src = ''
    }
  }, [audioUrl, onParagraphChange])

  // Expose jumpToParagraph on the window for ChapterReader to call
  useEffect(() => {
    (window as unknown as Record<string, unknown>).__audioPlayerJumpTo = jumpToParagraph
    return () => { delete (window as unknown as Record<string, unknown>).__audioPlayerJumpTo }
  }, [jumpToParagraph])

  // ── Format time ──
  const formatTime = (seconds: number) => {
    const m = Math.floor(seconds / 60)
    const s = Math.floor(seconds % 60)
    return `${m}:${s.toString().padStart(2, '0')}`
  }

  // ── Progress percentage ──
  const progress = duration > 0 ? (currentTime / duration) * 100 : 0

  // ── Seek on progress bar click ──
  const handleSeek = (e: React.MouseEvent<HTMLDivElement>) => {
    if (!audioRef.current || !duration) return
    const rect = e.currentTarget.getBoundingClientRect()
    const ratio = Math.max(0, Math.min(1, (e.clientX - rect.left) / rect.width))
    audioRef.current.currentTime = ratio * duration
  }

  // ── Collapsed state: just a small "Listen" button ──
  if (!isExpanded) {
    return (
      <button
        onClick={() => setIsExpanded(true)}
        className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium btn-transition"
        style={{
          backgroundColor: 'var(--bg-card)',
          color: 'var(--text-primary)',
          border: '1px solid var(--border-default)',
        }}
      >
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M3 18v-6a9 9 0 0 1 18 0v6" />
          <path d="M21 19a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3zM3 19a2 2 0 0 0 2 2h1a2 2 0 0 0 2-2v-3a2 2 0 0 0-2-2H3z" />
        </svg>
        Listen to this chapter
        <span className="text-xs" style={{ color: 'var(--text-secondary)' }}>
          · {formatTime(totalDuration)} · Read by {reader}
        </span>
      </button>
    )
  }

  // ── Expanded player ──
  return (
    <div
      className="rounded-xl border overflow-hidden animate-fade-in"
      style={{
        backgroundColor: 'var(--bg-card)',
        borderColor: 'var(--border-default)',
      }}
    >
      {/* Header with reader credit */}
      <div
        className="flex items-center justify-between px-4 py-2 text-xs"
        style={{ borderBottom: '1px solid var(--border-default)' }}
      >
        <div className="flex items-center gap-2">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ color: 'var(--accent-purple)' }}>
            <path d="M3 18v-6a9 9 0 0 1 18 0v6" />
            <path d="M21 19a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3zM3 19a2 2 0 0 0 2 2h1a2 2 0 0 0 2-2v-3a2 2 0 0 0-2-2H3z" />
          </svg>
          <span style={{ color: 'var(--text-secondary)' }}>
            Read by <strong style={{ color: 'var(--text-primary)' }}>{reader}</strong>
            <span className="ml-1" style={{ color: 'var(--text-tertiary, var(--text-secondary))' }}>
              · LibriVox · Public Domain
            </span>
          </span>
        </div>
        <button
          onClick={() => {
            if (isPlaying) {
              audioRef.current?.pause()
              setIsPlaying(false)
              if (animationRef.current) cancelAnimationFrame(animationRef.current)
            }
            setIsExpanded(false)
          }}
          className="p-1 rounded-md btn-transition"
          style={{ color: 'var(--text-secondary)' }}
          aria-label="Close audio player"
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" />
          </svg>
        </button>
      </div>

      {/* Progress bar — clickable */}
      <div
        className="h-1.5 cursor-pointer relative"
        style={{ backgroundColor: 'var(--bg-page)' }}
        onClick={handleSeek}
        role="slider"
        aria-label="Audio progress"
        aria-valuemin={0}
        aria-valuemax={100}
        aria-valuenow={Math.round(progress)}
      >
        <div
          className="h-full"
          style={{
            width: `${progress}%`,
            backgroundColor: 'var(--accent-purple)',
            transition: 'width 100ms linear',
          }}
        />
      </div>

      {/* Controls */}
      <div className="flex items-center justify-between px-4 py-2.5">
        <div className="flex items-center gap-1">
          {/* Skip back 15s */}
          <button
            onClick={() => skip(-15)}
            className="p-2 rounded-lg btn-transition"
            style={{ color: 'var(--text-secondary)' }}
            aria-label="Skip back 15 seconds"
          >
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M11 17l-5-5 5-5" /><path d="M18 17l-5-5 5-5" />
            </svg>
          </button>

          {/* Play/Pause */}
          <button
            onClick={togglePlay}
            className="p-2.5 rounded-full btn-transition"
            style={{
              backgroundColor: 'var(--accent-purple)',
              color: 'var(--text-inverse)',
            }}
            aria-label={isPlaying ? 'Pause' : 'Play'}
          >
            {isLoading ? (
              <svg width="20" height="20" viewBox="0 0 24 24" className="animate-spin">
                <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="2" fill="none" strokeDasharray="30 60" />
              </svg>
            ) : isPlaying ? (
              <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                <rect x="6" y="4" width="4" height="16" rx="1" />
                <rect x="14" y="4" width="4" height="16" rx="1" />
              </svg>
            ) : (
              <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                <polygon points="5,3 19,12 5,21" />
              </svg>
            )}
          </button>

          {/* Skip forward 15s */}
          <button
            onClick={() => skip(15)}
            className="p-2 rounded-lg btn-transition"
            style={{ color: 'var(--text-secondary)' }}
            aria-label="Skip forward 15 seconds"
          >
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M13 17l5-5-5-5" /><path d="M6 17l5-5-5-5" />
            </svg>
          </button>
        </div>

        {/* Time display */}
        <div className="text-xs font-mono" style={{ color: 'var(--text-secondary)' }}>
          {formatTime(currentTime)} / {formatTime(duration || totalDuration)}
        </div>

        {/* Speed control */}
        <button
          onClick={cycleSpeed}
          className="px-2.5 py-1 rounded-md text-xs font-bold btn-transition"
          style={{
            backgroundColor: 'var(--bg-page)',
            color: 'var(--text-secondary)',
            border: '1px solid var(--border-default)',
          }}
          aria-label={`Playback speed: ${playbackRate}x`}
        >
          {playbackRate}×
        </button>
      </div>
    </div>
  )
}
